data :
  pickle_dir : '../pickles/'
  # pickle_name : 'uav_sfcn_train_small.pickle'S
  # pickle_name : 'uav_sfcn_train_small_2048.pickle'
  pickle_name : 'uav_sfcn_patch_2048_ver3.pickle'
  
  
  val_pickle_name : ''
  
  shuffle :  True
  val_holdout_frac : 0.2
  result_dir : 'checkpoints'
  
training :
  gpu :
    use : True
    id : 2
  seed : 42
  epochs : 10000
  weight_decay : 0.0001 
  n_classes : 8 # uav : 8 / city : 20 
  patience :  30
  init_lr : 0.001
  optim : 'Adam'
  batch_size : 10000
  eval_interval : 100
  save_best_epoch_pth : True
  
learning_rate :
  scheduler : True
  lr_scheduler : 'step' 
  eta_min : 0.00001 # cosine option
  T_max : 400 # cosine option
  gamma : 0.5  #step option
  milsestone : [200, 300, 400, 500]  # step option
  
  
test :
  test_pickle_name : 'uav_sfcn_val_small.pickle'
  # test_pickle_name : 'uav_sfcn_val_origin.pickle'
  # test_pickle_name : 'uav_sfcn_patch_val_512.pickle'
  wandb_name :  'uav_patch_0.001_Adam_256_256_10_10000_sage_12_splce_1639017980'
  # train_id :  '1637235526'
  ckpt_file : 'epoch_035_ckpt.pth'
  # ckpt_file : 'epoch_132_ckpt.pth'

  ckpt_dir : 'checkpoints'
  save_result_dir : 'results'
  
# sampler options
sampler :
  sampler_true : True
  sampler_neighbor : [3,3,3,3,3,3,3,3,3,3]
  sampler_weight : [1, 1, 1, 1, 1, 1, 1, 1]
  
# wandb options
wandb : True
wandb_proj_name : 'MLVU_project_sampler'


# model optionss

in_dim : 5
loss : 'splce' # ce, wce, spl, tvs
in_feat_dropout : 0
dropout : 0

# dgl_builtin : True
dgl_builtin : True
# if dgl_builtin is False, sage_aggregator is matter
sage_aggregator : 'mean' # 'mean' 
multi_scale_mode : 
  use_multi_scale : False
  layer_scale_1 : 2
  layer_scale_2 : 4
  layer_scale_3 : 8
  
# https://docs.dgl.ai/en/0.6.x/api/python/nn.pytorch.html#relgraphconv
# [sage, densesage, cheb, tag, sg, graph]

conv_type : 'sage' # default : sage
batch_norm : True
residual : False
readout : 0.5
hidden_dim : 256
out_dim : 256
Layer : 10
tag_kernal : 10
